networks:
  agent-net:
    driver: bridge

services:
  agent:
    build:
      context: ../..
      dockerfile: bin/discovery_demo/Dockerfile
      target: final
    environment:
      DISCOVERY_PORT: 4000
      DISCOVERY_INTERVAL: 10
      AGENT_TTL: 60
      AGENT_CLEANUP_INTERVAL: 10
    networks:
      - agent-net
