networks:
  agent-net:
    driver: bridge

services:
  agent:
    build:
      context: ../..
      dockerfile: bin/transport_demo/Dockerfile
      target: final
    environment:
      BROADCAST_PORT: 4000
      BROADCAST_INTERVAL: 10
    networks:
      - agent-net
